[package]
name = "meld"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
home = "0.5"
chrono = { version = "0.4", features = ["serde"] }